export HOST="${TEST_NAME}.herokuapp.com"
export ASSET_HOST="${TEST_NAME}.herokuapp.com"
export RESQUE_REDIS_URL=$REDISCLOUD_URL
export CURRENCY_REDIS_URL=$REDISCLOUD_URL
export THROTTLED_REDIS_URL=$REDISCLOUD_URL
