# resources:
# - https://github.com/kubernetes-sigs/kustomize//examples/multibases?timeout=120&ref=v3.3.1
# nameSpace: remote-
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md


resources:
- ./sinatra-printer
