apiVersion: herokuapps.heroku.com/v1alpha1
kind: HerokuApp
metadata:
  name: sinatra-printer
spec:
  pipeline:
  - cluster: sinatra-printer-09243
    dynos:
    - web: 2:performance-m
    - worker: 1:performance-l
