# namespace: sinatra-printer
commonLabels:
  app: sinatra-printer
namePrefix:
  sinatra-printer-

resources:
- github.com/chap/clusters//src/defaults/app #?ref=v1alpha1&timeout=30
- github.com/chap/clusters//src/defaults/web #?ref=v1alpha1&timeout=30
# - github.com/chap/clusters//src/defaults/web-canary #?ref=v1alpha1&timeout=30
- github.com/chap/clusters//src/defaults/worker #?ref=v1alpha1&timeout=30

patches:
- target:
    kind: HerokuApp
  patch: |-
    - op: add
      path: /spec/deploy
      value:
        - - name: sandbox
            cluster: sinatra-sandbox-09234r
            url: https://1.2.3.4 # can we automatically generate this?
            source: github.com/chap/sinatra-printer/.heroku/apps/sinatra-printer//sandbox?ref=sandbox
            continueOn:
              fail: true
              error: true
          - name: sandbox-eu
            cluster: sinatra-sandbox-eu-09234r
            url: https://1.2.3.4 # can we automatically generate this?
            source: github.com/chap/sinatra-printer/.heroku/apps/sinatra-printer//sandbox?ref=sandbox
            # TODO: avoid duplicate, simultanous builds???
            # maybe builds only occur on target #1???
            continueOn:
              fail: true
              error: true
        - - name: qa
            cluster: sinatra-qa-09234r
            url: https://1.2.3.4 # can we automatically generate this?
            source: github.com/chap/sinatra-printer/.heroku/apps/sinatra-printer//qa?ref=main
        - - name: staging
            cluster: sinatra-staging-09234r
            url: https://1.2.3.4 # can we automatically generate this?
            source: github.com/chap/sinatra-printer/.heroku/apps/sinatra-printer//staging?ref=main
        - - name: production
            cluster: sinatra-production-09234r
            url: https://1.2.3.4 # can we automatically generate this?
            source: github.com/chap/sinatra-printer/.heroku/apps/sinatra-printer//production?ref=sandbox
          - name: production-eu
            cluster: sinatra-production-eu-09234r
            url: https://1.2.3.4 # can we automatically generate this?
            source: github.com/chap/sinatra-printer/.heroku/apps/sinatra-printer//production-eu?ref=sandbox

# TODO: can this move to the defaults???
#       override `command` per process???
images:
- name: DEFAULT
  newName: ghcr.io/chap/sinatra-printer
  newTag: latest
