# repo: https://github.com/chap/sinatra-printer
# maintenance: false
# build: heroku-buildpack.yaml

# https://github.com/chap/sinatra-printer/tree/master/.heroku/defaults

resources:
- ./web.yaml
# - https://github.com/chap/sinatra-printer/tree/master//.heroku/defaults/?timeout=120&ref=main
namePrefix: dev-