on:
  push:

permissions:
  packages: write

jobs:
  buildpack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: build
      run: |
        # install buildpack CLI
        (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.32.1/pack-v0.32.1-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
        
        # build
        pack build $GITHUB_REPOSITORY --builder heroku/builder:22 --path ./
        docker tag $GITHUB_REPOSITORY ghcr.io/$GITHUB_REPOSITORY:latest

        # publish
        docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
        docker push ghcr.io/$GITHUB_REPOSITORY:latest
