on:
  push:

jobs:
  my_job:
    runs-on: ubuntu-latest
    # container: buildpacksio/pack:latest
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    - name: suggest
      # run: pack builder suggest
      run: |
        (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.32.1/pack-v0.32.1-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
        pack builder suggest
        
        # pack build sinatra-printer --path ./ --builder heroku/builder:22

        # git clone https://github.com/heroku/ruby-getting-started
        # cd ruby-getting-started
        pack build $GITHUB_REPOSITORY --builder heroku/builder:22 --path ./

        # docker push ghcr.io/$GITHUB_REPOSITORY:latest